name: churchdata_core
description: core library for Church projects

version: 0.2.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  android_alarm_manager_plus: ^2.0.5
  async: ^2.8.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.10
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.10
  firebase_database: ^9.0.8
  firebase_dynamic_links: ^4.1.0
  firebase_messaging: ^11.2.10
  firebase_storage: ^10.2.9
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^9.4.0
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.2
  google_maps_flutter_web: ^0.3.2+1
  google_sign_in: ^5.2.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  rxdart: ^0.27.3
  sentry_flutter: ^6.3.0
  timeago: ^3.2.2
  tinycolor2: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.20
  group_list_view: ^1.1.1
  share_plus: ^4.0.3
  firebase_remote_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  churchdata_core_mocks:
    git:
      url: https://github.com/Andrew-Bekhiet/churchdata_core_mocks
      ref: master
  mockito: ^5.1.0
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  hive_generator: ^1.1.2

flutter:
  assets:
    - assets/Logo.png
    - assets/whatsapp.png
