name: churchdata_core
description: core library for Church projects

version: 0.4.0
publish_to: "none"
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependency_overrides:
  # churchdata_core_mocks:
  #   path: ../churchdata_core_mocks

dependencies:
  flutter:
    sdk: flutter

  android_alarm_manager_plus: ^2.1.0
  async: ^2.9.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.0.2
  cloud_functions: ^4.0.2
  copy_with_extension: ^4.0.2
  equatable: ^2.0.3
  firebase_auth: ^4.0.2
  firebase_database: ^10.0.2
  firebase_dynamic_links: ^5.0.1
  firebase_messaging: ^14.0.1
  firebase_storage: ^11.0.2
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^13.0.0
  flutter_secure_storage: ">=5.0.0 <8.0.0"
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.4.0+1
  google_sign_in: ^5.4.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  rxdart: ^0.27.4
  sentry_flutter: ^6.6.3
  timeago: ^3.2.2
  tinycolor2: ^3.0.1
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  share_plus: ^6.1.0
  firebase_remote_config: ^3.0.2
  version: ^3.0.2
  package_info_plus: ^3.0.0
  group_list_view:
    git:
      url: https://github.com/Andrew-Bekhiet/flutter_group_list_view
      ref: 0ebdffaebc8ccdd8d92072edfe2f1db567a7db9e
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  churchdata_core_mocks:
    git:
      url: https://github.com/Andrew-Bekhiet/churchdata_core_mocks
      ref: bbe570540caac2075e2486b7adc25da50a713a1a
  mockito: ^5.2.0
  build_runner: ^2.2.0
  copy_with_extension_gen: ^4.0.2
  hive_generator: ^2.0.0

flutter:
  assets:
    - assets/Logo.png
    - assets/whatsapp.png
