name: churchdata_core
description: core library for Church projects
version: 0.1.0
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  android_alarm_manager_plus: ^2.0.3
  async: ^2.8.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_database: ^9.0.5
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^9.2.0
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  google_sign_in: ^5.2.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  rxdart: ^0.27.3
  sentry_flutter: ^6.2.2
  timeago: ^3.1.0
  tinycolor2: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.17
  group_list_view: ^1.1.1
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  mockito: ^5.0.17
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  copy_with_extension_gen: ^4.0.0
  hive_generator: ^1.1.1
  hive_test: ^1.0.1
  fake_cloud_firestore:
    git:
      url: https://github.com/Andrew-Bekhiet/fake_cloud_firestore
      ref: 051a03a2a1d2064f19f17e12db2a71876308bac0
  firebase_storage_mocks: ^0.5.0
  firebase_auth_mocks: ^0.8.2
  firebase_database_mocks: ^0.3.2
  google_sign_in_mocks: ^0.2.1
  network_image_mock: ^2.0.1
  mock_data: ^2.0.0

flutter:
  assets:
    - assets/Logo.png
    - assets/whatsapp.png
