name: churchdata_core
description: core library for Church projects

version: 0.5.0
publish_to: "none"
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.1"

dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  android_alarm_manager_plus: ^4.0.2
  async: ^2.9.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  copy_with_extension: ^5.0.2
  equatable: ^2.0.3
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.0
  firebase_dynamic_links: ^6.0.2
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.0.0
  get_it: ^8.0.2
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.5.1
  google_sign_in: ^6.0.2
  hive_flutter: ^1.1.0
  intl: ">=0.18.0 <0.21.0"
  rxdart: ^0.28.0
  sentry_flutter: ^8.3.0
  timeago: ^3.2.2
  tinycolor2: ^3.0.1
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  share_plus: ^10.0.0
  firebase_remote_config: ^5.0.2
  version: ^3.0.2
  package_info_plus: ^8.0.0
  group_list_view:
    git:
      url: https://github.com/Andrew-Bekhiet/flutter_group_list_view
      ref: 0ebdffaebc8ccdd8d92072edfe2f1db567a7db9e
  visibility_detector: ^0.4.0+2
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  churchdata_core_mocks:
    git:
      url: https://github.com/Andrew-Bekhiet/churchdata_core_mocks
      ref: master
  mockito: ^5.2.0
  build_runner: ^2.3.2
  copy_with_extension_gen: ^5.0.2
  hive_generator: ^2.0.0

flutter:
  assets:
    - assets/Logo.png
    - assets/whatsapp.png
